# Shared source list for the native reference product and browser application.
set(SURGE_XT_SOURCES
  SurgeSynthEditor.cpp
  SurgeSynthEditor.h
  SurgeSynthProcessor.cpp
  SurgeSynthProcessor.h

  SurgeCLAPPresetDiscovery.cpp

  util/LuaTokeniserSurge.cpp
  util/LuaTokeniserSurge.h

  util/LockFreeStack.h

  gui/AccessibleHelpers.h
  gui/ModulationGridConfiguration.h
  gui/RefreshableOverlay.h
  gui/RuntimeFont.cpp
  gui/RuntimeFont.h
  gui/SkinFontLoader.cpp
  gui/SkinImageMaps.h
  gui/SkinSupport.cpp
  gui/SkinSupport.h
  gui/SurgeGUICallbackInterfaces.h
  gui/SurgeGUIEditor.cpp
  gui/SurgeGUIEditor.h
  gui/SurgeGUIEditorHtmlGenerators.cpp
  gui/SurgeGUIEditorInfowindow.cpp
  gui/SurgeGUIEditorOverlays.cpp
  gui/SurgeGUIEditorTags.h
  gui/SurgeGUIEditorValueCallbacks.cpp
  gui/SurgeGUIEditorMenuStructures.cpp
  gui/SurgeGUIUtils.cpp
  gui/SurgeGUIUtils.h
  gui/SurgeImage.cpp
  gui/SurgeImage.h
  gui/SurgeImageStore.cpp
  gui/SurgeImageStore.h
  gui/SurgeJUCEHelpers.h
  gui/SurgeJUCELookAndFeel.cpp
  gui/SurgeJUCELookAndFeel.h
  gui/UndoManager.cpp
  gui/overlays/AboutScreen.cpp
  gui/overlays/AboutScreen.h
  gui/overlays/FilterAnalysis.cpp
  gui/overlays/FilterAnalysis.h
  gui/overlays/KeyBindingsOverlay.h
  gui/overlays/KeyBindingsOverlay.cpp
  gui/overlays/LuaEditors.cpp
  gui/overlays/LuaEditors.h
  gui/overlays/MSEGEditor.cpp
  gui/overlays/MSEGEditor.h
  gui/overlays/MSEGEditorAccessibleKeyboard.cpp
  gui/overlays/MSEGEditorAccessibleKeyboard.h
  gui/overlays/MiniEdit.cpp
  gui/overlays/MiniEdit.h
  gui/overlays/Alert.cpp
  gui/overlays/Alert.h
  gui/overlays/OverlayUtils.h
  gui/overlays/OverlayUtils.cpp
  gui/overlays/ModulationEditor.cpp
  gui/overlays/ModulationEditor.h
  gui/overlays/Oscilloscope.cpp
  gui/overlays/Oscilloscope.h
  gui/overlays/OverlayWrapper.cpp
  gui/overlays/OverlayWrapper.h
  gui/overlays/PatchDBViewer.cpp
  gui/overlays/PatchDBViewer.h
  gui/overlays/PatchStoreDialog.cpp
  gui/overlays/PatchStoreDialog.h
  gui/overlays/TuningOverlays.cpp
  gui/overlays/TuningOverlays.h
  gui/overlays/TypeinParamEditor.cpp
  gui/overlays/TypeinParamEditor.h
  gui/overlays/WaveShaperAnalysis.cpp
  gui/overlays/WaveShaperAnalysis.h
  gui/overlays/OpenSoundControlSettings.cpp
  gui/widgets/CurrentFxDisplay.cpp
  gui/widgets/CurrentFxDisplay.h
  gui/widgets/EffectChooser.cpp
  gui/widgets/EffectChooser.h
  gui/widgets/EffectLabel.h
  gui/widgets/LFOAndStepDisplay.cpp
  gui/widgets/LFOAndStepDisplay.h
  gui/widgets/MainFrame.cpp
  gui/widgets/MainFrame.h
  gui/widgets/MenuButtonFromAsset.cpp
  gui/widgets/MenuButtonFromAsset.h
  gui/widgets/MenuCustomComponents.cpp
  gui/widgets/MenuCustomComponents.h
  gui/widgets/MenuForDiscreteParams.cpp
  gui/widgets/MenuForDiscreteParams.h
  gui/widgets/ModulatableControlInterface.h
  gui/widgets/ModulatableSlider.cpp
  gui/widgets/ModulatableSlider.h
  gui/widgets/ModulationSourceButton.cpp
  gui/widgets/ModulationSourceButton.h
  gui/widgets/MultiSwitch.cpp
  gui/widgets/MultiSwitch.h
  gui/widgets/NumberField.cpp
  gui/widgets/NumberField.h
  gui/widgets/OscillatorWaveformDisplay.cpp
  gui/widgets/OscillatorWaveformDisplay.h
  gui/widgets/ParameterInfowindow.cpp
  gui/widgets/ParameterInfowindow.h
  gui/widgets/PatchSelector.cpp
  gui/widgets/PatchSelector.h
  gui/widgets/Switch.cpp
  gui/widgets/Switch.h
  gui/widgets/SurgeTextButton.cpp
  gui/widgets/Tooltip.cpp
  gui/widgets/Tooltip.h
  gui/widgets/WtGenSpinner.h
  gui/widgets/TypeAheadTextEditor.cpp
  gui/widgets/VerticalLabel.cpp
  gui/widgets/VerticalLabel.h
  gui/widgets/VuMeter.cpp
  gui/widgets/VuMeter.h
  gui/widgets/WaveShaperSelector.cpp
  gui/widgets/WaveShaperSelector.h
  gui/widgets/WidgetBaseMixin.h
  gui/widgets/XMLConfiguredMenus.cpp
  gui/widgets/XMLConfiguredMenus.h

  osc/OpenSoundControl.cpp
  osc/OpenSoundControl.h
)


list(TRANSFORM SURGE_XT_SOURCES PREPEND "${CMAKE_CURRENT_LIST_DIR}/")
target_sources(${PROJECT_NAME} PRIVATE ${SURGE_XT_SOURCES})
