#!/bin/sh

if [[ ! -f build-osx.sh ]]; then
    echo "Please run build-version-override.sh from the root of the surge git directory"
    exit 1
fi

rm -f VERSION_GIT_INFO
echo "# This file is generated by our pipeline so we can construct version information without git" > VERSION_GIT_INFO
git rev-parse --abbrev-ref HEAD >> VERSION_GIT_INFO
git log -1 --format=%h >> VERSION_GIT_INFO
