#!/bin/sh

if [ ! -f CMakeLists.txt ]; then
    echo "Please run build-version-override.sh from the root of the surge git directory"
    exit 1
fi

(
    echo "# This file is generated by our pipeline so we can construct version information without git"
    git rev-parse --abbrev-ref HEAD
    git rev-parse --short HEAD
) > VERSION_GIT_INFO
