function init(state)
    print("\nInit block\n")

    print("amplitude", state.amplitude)
    print("attack", state.attack)
    print("block_size", state.block_size)
    print("cc_breath", state.cc_breath)
    print("cc_expr", state.cc_expr)
    print("cc_mw", state.cc_mw)
    print("cc_sus", state.cc_sus)
    print("chan_at", state.chan_at)
    print("clamp_output", state.clamp_output)
    print("cycle", state.cycle)
    print("decay", state.decay)
    print("deform", state.deform)
    print("delay", state.delay)
    print("highest_key", state.highest_key)
    print("hold", state.hold)
    print("intphase", state.intphase)
    print("is_rendering_to_ui", state.is_rendering_to_ui)
    print("is_voice", state.is_voice)
    print("key", state.key)
    print("latest_key", state.latest_key)
    print("lowest_key", state.lowest_key)
    print("mpe_bend", state.mpe_bend)
    print("mpe_bendrange", state.mpe_bendrange)
    print("mpe_enabled", state.mpe_enabled)
    print("mpe_pressure", state.mpe_pressure)
    print("mpe_timbre", state.mpe_timbre)
    print("pb", state.pb)
    print("pb_range_dn", state.pb_range_dn)
    print("pb_range_up", state.pb_range_up)
    print("phase", state.phase)
    print("play_mode", state.play_mode)
    print("poly_at", state.poly_at)
    print("poly_limit", state.poly_limit)
    print("rate", state.rate)
    print("rel_velocity", state.rel_velocity)
    print("release", state.release)
    print("released", state.released)
    print("samplerate", state.samplerate)
    print("scene_mode", state.scene_mode)
    print("songpos", state.songpos)
    print("split_point", state.split_point)
    print("startphase", state.startphase)
    print("sustain", state.sustain)
    print("tempo", state.tempo)
    print("tuned_key", state.tuned_key)
    print("use_amplitude", state.use_amplitude)
    print("use_envelope", state.use_envelope)
    print("velocity", state.velocity)
    print("voice_count", state.voice_count)
    print("voice_id", state.voice_id)

    return state
end

function process(state)
    if not state.init then
        state.init = true

        print("\nProcess block\n")

        print("amplitude", state.amplitude)
        print("attack", state.attack)
        print("block_size", state.block_size)
        print("cc_breath", state.cc_breath)
        print("cc_expr", state.cc_expr)
        print("cc_mw", state.cc_mw)
        print("cc_sus", state.cc_sus)
        print("chan_at", state.chan_at)
        print("clamp_output", state.clamp_output)
        print("cycle", state.cycle)
        print("decay", state.decay)
        print("deform", state.deform)
        print("delay", state.delay)
        print("highest_key", state.highest_key)
        print("hold", state.hold)
        print("intphase", state.intphase)
        print("is_rendering_to_ui", state.is_rendering_to_ui)
        print("is_voice", state.is_voice)
        print("key", state.key)
        print("latest_key", state.latest_key)
        print("lowest_key", state.lowest_key)
        print("mpe_bend", state.mpe_bend)
        print("mpe_bendrange", state.mpe_bendrange)
        print("mpe_enabled", state.mpe_enabled)
        print("mpe_pressure", state.mpe_pressure)
        print("mpe_timbre", state.mpe_timbre)
        print("pb", state.pb)
        print("pb_range_dn", state.pb_range_dn)
        print("pb_range_up", state.pb_range_up)
        print("phase", state.phase)
        print("play_mode", state.play_mode)
        print("poly_at", state.poly_at)
        print("poly_limit", state.poly_limit)
        print("rate", state.rate)
        print("rel_velocity", state.rel_velocity)
        print("release", state.release)
        print("released", state.released)
        print("samplerate", state.samplerate)
        print("scene_mode", state.scene_mode)
        print("songpos", state.songpos)
        print("split_point", state.split_point)
        print("startphase", state.startphase)
        print("sustain", state.sustain)
        print("tempo", state.tempo)
        print("tuned_key", state.tuned_key)
        print("use_amplitude", state.use_amplitude)
        print("use_envelope", state.use_envelope)
        print("velocity", state.velocity)
        print("voice_count", state.voice_count)
        print("voice_id", state.voice_id)

    end

    state.output = 0

    return state
end