
/*
** THIS IS AN AUTOMATICALLY GENERATED FILE. DO NOT EDIT IT
**
** If you need to modify this file, please read the comment
** in scripts/win/emit-vector-rc.py
**
** This file defined the constants IDB_BG_SCALE_300 and the
** like as explicit values so the .rc compiler (which cannot
** add identifiers as integers) can include assets.
**
** You can address these items as IDB_BG_SCALE_300 or
** IDB_BG + SCALE_OFFSET_300 in your non-rc code.
*/


// Offset IDB_ABOUT by SCALABLE_100_OFFSET value and so on
#define IDB_ABOUT_SCALE_SVG 80158

// Offset IDB_BG by SCALABLE_100_OFFSET value and so on
#define IDB_BG_SCALE_SVG 80102

// Offset IDB_BUTTON_ABOUT by SCALABLE_100_OFFSET value and so on
#define IDB_BUTTON_ABOUT_SCALE_SVG 80159

// Offset IDB_BUTTON_CHECK by SCALABLE_100_OFFSET value and so on
#define IDB_BUTTON_CHECK_SCALE_SVG 80150

// Offset IDB_BUTTON_MENU by SCALABLE_100_OFFSET value and so on
#define IDB_BUTTON_MENU_SCALE_SVG 80164

// Offset IDB_BUTTON_MINUSPLUS by SCALABLE_100_OFFSET value and so on
#define IDB_BUTTON_MINUSPLUS_SCALE_SVG 80149

// Offset IDB_BUTTON_STORE by SCALABLE_100_OFFSET value and so on
#define IDB_BUTTON_STORE_SCALE_SVG 80148

// Offset IDB_CHARACTER by SCALABLE_100_OFFSET value and so on
#define IDB_CHARACTER_SCALE_SVG 80161

// Offset IDB_CONF by SCALABLE_100_OFFSET value and so on
#define IDB_CONF_SCALE_SVG 80135

// Offset IDB_ENVMODE by SCALABLE_100_OFFSET value and so on
#define IDB_ENVMODE_SCALE_SVG 80162

// Offset IDB_ENVSHAPE by SCALABLE_100_OFFSET value and so on
#define IDB_ENVSHAPE_SCALE_SVG 80145

// Offset IDB_FADERH_BG by SCALABLE_100_OFFSET value and so on
#define IDB_FADERH_BG_SCALE_SVG 80154

// Offset IDB_FADERH_HANDLE by SCALABLE_100_OFFSET value and so on
#define IDB_FADERH_HANDLE_SCALE_SVG 80153

// Offset IDB_FADERH_LABELS by SCALABLE_100_OFFSET value and so on
#define IDB_FADERH_LABELS_SCALE_SVG 80131

// Offset IDB_FADERV_BG by SCALABLE_100_OFFSET value and so on
#define IDB_FADERV_BG_SCALE_SVG 80105

// Offset IDB_FADERV_HANDLE by SCALABLE_100_OFFSET value and so on
#define IDB_FADERV_HANDLE_SCALE_SVG 80157

// Offset IDB_FBCONFIG by SCALABLE_100_OFFSET value and so on
#define IDB_FBCONFIG_SCALE_SVG 80112

// Offset IDB_FILTERBUTTONS by SCALABLE_100_OFFSET value and so on
#define IDB_FILTERBUTTONS_SCALE_SVG 80108

// Offset IDB_FILTERSUBTYPE by SCALABLE_100_OFFSET value and so on
#define IDB_FILTERSUBTYPE_SCALE_SVG 80160

// Offset IDB_FILTER_GLYPHS by SCALABLE_100_OFFSET value and so on
#define IDB_FILTER_GLYPHS_SCALE_SVG 80169

// Offset IDB_FMCONFIG by SCALABLE_100_OFFSET value and so on
#define IDB_FMCONFIG_SCALE_SVG 80151

// Offset IDB_FXBYPASS by SCALABLE_100_OFFSET value and so on
#define IDB_FXBYPASS_SCALE_SVG 80144

// Offset IDB_FXCONF by SCALABLE_100_OFFSET value and so on
#define IDB_FXCONF_SCALE_SVG 80137

// Offset IDB_FXCONF_SYMBOLS by SCALABLE_100_OFFSET value and so on
#define IDB_FXCONF_SYMBOLS_SCALE_SVG 80136

// Offset IDB_LFOTRIGGER by SCALABLE_100_OFFSET value and so on
#define IDB_LFOTRIGGER_SCALE_SVG 80146

// Offset IDB_LFOTYPE by SCALABLE_100_OFFSET value and so on
#define IDB_LFOTYPE_SCALE_SVG 80166

// Offset IDB_MENU_IN_FILTER_BG by SCALABLE_100_OFFSET value and so on
#define IDB_MENU_IN_FILTER_BG_SCALE_SVG 80168

// Offset IDB_MENU_IN_SLIDER_BG by SCALABLE_100_OFFSET value and so on
#define IDB_MENU_IN_SLIDER_BG_SCALE_SVG 80167

// Offset IDB_MINIEDIT_ICON by SCALABLE_100_OFFSET value and so on
#define IDB_MINIEDIT_ICON_SCALE_SVG 80170

// Offset IDB_MODSRC_BG by SCALABLE_100_OFFSET value and so on
#define IDB_MODSRC_BG_SCALE_SVG 80124

// Offset IDB_MODSRC_SYMBOL by SCALABLE_100_OFFSET value and so on
#define IDB_MODSRC_SYMBOL_SCALE_SVG 80128

// Offset IDB_MPE_BUTTON by SCALABLE_100_OFFSET value and so on
#define IDB_MPE_BUTTON_SCALE_SVG 80171

// Offset IDB_MSEG_HORIZONTAL_SNAP by SCALABLE_100_OFFSET value and so on
#define IDB_MSEG_HORIZONTAL_SNAP_SCALE_SVG 80304

// Offset IDB_MSEG_MOVEMENT by SCALABLE_100_OFFSET value and so on
#define IDB_MSEG_MOVEMENT_SCALE_SVG 80302

// Offset IDB_MSEG_SEGMENT_HANDLES by SCALABLE_100_OFFSET value and so on
#define IDB_MSEG_SEGMENT_HANDLES_SCALE_SVG 80301

// Offset IDB_MSEG_VERTICAL_SNAP by SCALABLE_100_OFFSET value and so on
#define IDB_MSEG_VERTICAL_SNAP_SCALE_SVG 80303

// Offset IDB_NUMBERS by SCALABLE_100_OFFSET value and so on
#define IDB_NUMBERS_SCALE_SVG 80127

// Offset IDB_OCTAVES by SCALABLE_100_OFFSET value and so on
#define IDB_OCTAVES_SCALE_SVG 80118

// Offset IDB_OCTAVES_OSC by SCALABLE_100_OFFSET value and so on
#define IDB_OCTAVES_OSC_SCALE_SVG 80117

// Offset IDB_OSCMENU by SCALABLE_100_OFFSET value and so on
#define IDB_OSCMENU_SCALE_SVG 80119

// Offset IDB_OSCROUTE by SCALABLE_100_OFFSET value and so on
#define IDB_OSCROUTE_SCALE_SVG 80143

// Offset IDB_OSCSELECT by SCALABLE_100_OFFSET value and so on
#define IDB_OSCSELECT_SCALE_SVG 80122

// Offset IDB_OSCSWITCH by SCALABLE_100_OFFSET value and so on
#define IDB_OSCSWITCH_SCALE_SVG 80110

// Offset IDB_POLYMODE by SCALABLE_100_OFFSET value and so on
#define IDB_POLYMODE_SCALE_SVG 80123

// Offset IDB_RELATIVE_TOGGLE by SCALABLE_100_OFFSET value and so on
#define IDB_RELATIVE_TOGGLE_SCALE_SVG 80121

// Offset IDB_SCENEMODE by SCALABLE_100_OFFSET value and so on
#define IDB_SCENEMODE_SCALE_SVG 80114

// Offset IDB_SCENESWITCH by SCALABLE_100_OFFSET value and so on
#define IDB_SCENESWITCH_SCALE_SVG 80113

// Offset IDB_STOREPATCH by SCALABLE_100_OFFSET value and so on
#define IDB_STOREPATCH_SCALE_SVG 80163

// Offset IDB_SWITCH_FM by SCALABLE_100_OFFSET value and so on
#define IDB_SWITCH_FM_SCALE_SVG 80133

// Offset IDB_SWITCH_KTRK by SCALABLE_100_OFFSET value and so on
#define IDB_SWITCH_KTRK_SCALE_SVG 80125

// Offset IDB_SWITCH_LINK by SCALABLE_100_OFFSET value and so on
#define IDB_SWITCH_LINK_SCALE_SVG 80140

// Offset IDB_SWITCH_MUTE by SCALABLE_100_OFFSET value and so on
#define IDB_SWITCH_MUTE_SCALE_SVG 80134

// Offset IDB_SWITCH_RETRIGGER by SCALABLE_100_OFFSET value and so on
#define IDB_SWITCH_RETRIGGER_SCALE_SVG 80126

// Offset IDB_SWITCH_SOLO by SCALABLE_100_OFFSET value and so on
#define IDB_SWITCH_SOLO_SCALE_SVG 80132

// Offset IDB_SWITCH_TEMPOSYNC by SCALABLE_100_OFFSET value and so on
#define IDB_SWITCH_TEMPOSYNC_SCALE_SVG 80140

// Offset IDB_TUNE_BUTTON by SCALABLE_100_OFFSET value and so on
#define IDB_TUNE_BUTTON_SCALE_SVG 80173

// Offset IDB_UNIPOLAR by SCALABLE_100_OFFSET value and so on
#define IDB_UNIPOLAR_SCALE_SVG 80152

// Offset IDB_VFADER_MINI_BG_BLACK by SCALABLE_100_OFFSET value and so on
#define IDB_VFADER_MINI_BG_BLACK_SCALE_SVG 80141

// Offset IDB_WAVESHAPER by SCALABLE_100_OFFSET value and so on
#define IDB_WAVESHAPER_SCALE_SVG 80120

// Offset IDB_ZOOM_BUTTON by SCALABLE_100_OFFSET value and so on
#define IDB_ZOOM_BUTTON_SCALE_SVG 80172


#define IDB_POLYSPLIT_NUM_BG_SCALE_SVG 80174


#define IDB_PITCHBEND_NUM_BG_SCALE_SVG 80175


#define IDB_KEYTRACKROOT_BG_SCALE_SVG 80176


#define IDB_MSEG_LOOP_MODES_SCALE_SVG 80305


#define IDB_LFO_MSEG_EDIT_SCALE_SVG 80177


#define IDB_LFO_PRESETS_SCALE_SVG 80178


#define IDB_MSEG_NUMBERFIELDBG_SCALE_SVG 80306
