if(EXISTS "${ASIO_SDK_DESTINATION}/asiosdk/readme.txt")
    message( STATUS "ASIO SDK already downloaded to ${ASIO_SDK_DESTINATION}")
else()
    message(STATUS "Downloading ASIO SDK to ${ASIO_SDK_DESTINATION}")
    file( DOWNLOAD https://www.steinberg.net/asiosdk ${ASIO_SDK_DESTINATION}/asio.zip)
    file( ARCHIVE_EXTRACT INPUT ${ASIO_SDK_DESTINATION}/asio.zip DESTINATION ${ASIO_SDK_DESTINATION})
    file( GLOB ASIO_DIR LIST_DIRECTORIES TRUE "${ASIO_SDK_DESTINATION}/asiosdk_*" )
    file( RENAME ${ASIO_DIR} ${ASIO_SDK_DESTINATION}/asiosdk)
endif()
