set(CMAKE_SYSTEM_NAME Darwin)

set(CMAKE_C_COMPILER x86_64-apple-darwin20.4-clang)
set(CMAKE_CXX_COMPILER ${CMAKE_C_COMPILER}++)

set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
