#pragma once

//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by surge.rc
//
#define IDB_BG 102
#define IDB_FADERV_BG 105
#define IDD_EVALUE 107
#define IDB_OSCSWITCH 110
#define IDB_FBCONFIG 112
#define IDB_SCENESWITCH 113
#define IDB_SCENEMODE 114
#define IDB_OCTAVES_OSC 117
#define IDB_OCTAVES 118
#define IDB_OSCMENU 119
#define IDB_WAVESHAPER 120
#define IDB_RELATIVE_TOGGLE 121
#define IDB_OSCSELECT 122
#define IDB_POLYMODE 123
#define IDB_MODSRC_BG 124
#define IDB_SWITCH_KTRK 125
#define IDB_SWITCH_RETRIGGER 126
#define IDB_NUMBERS 127
#define IDB_MODSRC_SYMBOL 128
#define IDB_FADERH_LABELS 131
#define IDB_SWITCH_SOLO 132
#define IDB_SWITCH_FM 133
#define IDB_SWITCH_MUTE 134
#define IDB_FXCONF_SYMBOLS 136
#define IDB_FXCONF 137
#define IDB_SWITCH_TEMPOSYNC 140
#define IDB_SWITCH_LINK 140
#define IDB_VFADER_MINI_BG_BLACK 141
#define IDB_OSCROUTE 143
#define IDB_FXBYPASS 144
#define IDB_ENVSHAPE 145
#define IDB_LFOTRIGGER 146
#define IDD_SAVEPATCH 147
#define IDB_BUTTON_STORE 148
#define IDB_BUTTON_MINUSPLUS 149
#define IDB_BUTTON_CHECK 150
#define IDB_FMCONFIG 151
#define IDB_UNIPOLAR 152
#define IDB_FADERH_HANDLE 153
#define IDB_FADERH_BG 154
#define IDB_FADERV_HANDLE 157
#define IDB_FILTERSUBTYPE 160
#define IDI_ICON1 164
#define IDI_SURGE 164
#define IDR_PNG1 165
#define IDB_CHARACTER 161
#define IDB_ENVMODE 162
#define IDB_BUTTON_MENU 164
#define IDB_LFOTYPE 166
#define IDB_MENU_IN_SLIDER_BG 167
#define IDB_MENU_IN_FILTER_BG 168
#define IDB_FILTER_GLYPHS 169

// == SVG == Do not remove this comment - it indicates the start of the automated SVG adding block
#define IDB_MSEG_SEGMENT_HANDLES 301
#define IDB_MSEG_MOVEMENT 302
#define IDB_MINIEDIT_ICON 170
#define IDB_MSEG_VERTICAL_SNAP 303
#define IDB_MSEG_HORIZONTAL_SNAP 304
#define IDB_MPE_BUTTON 171
#define IDB_ZOOM_BUTTON 172
#define IDB_TUNE_BUTTON 173
#define IDB_POLYSPLIT_NUM_BG 174
#define IDB_PITCHBEND_NUM_BG 175
#define IDB_KEYTRACKROOT_BG 176
#define IDB_MSEG_LOOP_MODES 305
#define IDB_LFO_MSEG_EDIT 177
#define IDB_LFO_PRESETS 178
#define IDB_MSEG_NUMBERFIELDBG 306
#define IDB_MODSRC_SHOW_LFO 179
#define IDB_MSEG_EDIT_MODE 307
#define IDB_ABOUT_LOGOS 180
#define IDB_ABOUT 158
// == /SVG == Do not remove this comment


#define IDC_NAME 1001
#define IDC_CATEGORY 1002
#define IDC_DESCRIPTION 1003
#define IDC_AUTHOR 1004
#define IDC_TEDIT 1024
#define IDC_TPROMPT 1025


#define IDR_LATO_FONT 501

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 166
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 1005
#define _APS_NEXT_SYMED_VALUE 101
#endif
#endif

#if WINDOWS
#define SCALABLE_SVG_OFFSET 80000

#include "scalableresource.h" // found in src/windows

#endif
