#pragma once

//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by surge.rc
//
#define IDB_MAIN_BG 102
#define IDB_SLIDER_VERT_BG 105
#define IDB_ENTER_VALUE_LEGACY 107
#define IDB_FILTER_CONFIG 112
#define IDB_SCENE_SELECT 113
#define IDB_SCENE_MODE 114
#define IDB_OSC_OCTAVE 117
#define IDB_SCENE_OCTAVE 118
#define IDB_OSC_MENU 119
#define IDB_WAVESHAPER_MODE 120
#define IDB_FILTER2_OFFSET 121
#define IDB_OSC_SELECT 122
#define IDB_PLAY_MODE 123
#define IDB_OSC_KEYTRACK 125
#define IDB_OSC_RETRIGGER 126
#define IDB_MIXER_SOLO 132
#define IDB_MIXER_MUTE 134
#define IDB_FX_TYPE_ICONS 136
#define IDB_FX_GRID 137
#define IDB_FILTER2_RESONANCE_LINK 140
#define IDB_MIXER_OSC_ROUTING 143
#define IDB_FX_GLOBAL_BYPASS 144
#define IDB_ENV_SHAPE 145
#define IDB_LFO_TRIGGER_MODE 146
#define IDB_SAVE_PATCH 148
#define IDB_PREVNEXT_JOG 149
#define IDB_OSC_FM_ROUTING 151
#define IDB_LFO_UNIPOLAR 152
#define IDB_SLIDER_HORIZ_HANDLE 153
#define IDB_SLIDER_HORIZ_BG 154
#define IDB_SLIDER_VERT_HANDLE 157
#define IDB_FILTER_SUBTYPE 160
#define IDB_OSC_CHARACTER 161
#define IDB_ENV_MODE 162
#define IDI_MAIN_MENU 164
#define IDB_MAIN_MENU 164
#define IDB_LFO_TYPE 166
#define IDB_MENU_AS_SLIDER 167
#define IDB_FILTER_MENU 168
#define IDB_FILTER_ICONS 169
#define IDB_WAVESHAPER_BG 183
#define IDB_WAVESHAPER_ANALYSIS 184
#define IDB_MODMENU_ICONS 185
#define IDB_FAVORITE_BUTTON 186
#define IDB_SEARCH_BUTTON 187
#define IDB_FAVORITE_MENU_ICON 188
#define IDB_UNDO_BUTTON 189
#define IDB_REDO_BUTTON 190
#define IDB_FILTER_ANALYSIS 191

// == SVG == Do not remove this comment - it indicates the start of the automated SVG adding block
#define IDB_MSEG_NODES 301
#define IDB_MSEG_MOVEMENT_MODE 302
#define IDB_SURGE_ICON 170
#define IDB_MSEG_VERTICAL_SNAP 303
#define IDB_MSEG_HORIZONTAL_SNAP 304
#define IDB_MPE_BUTTON 171
#define IDB_ZOOM_BUTTON 172
#define IDB_TUNE_BUTTON 173
#define IDB_NUMFIELD_POLY_SPLIT 174
#define IDB_NUMFIELD_PITCHBEND 175
#define IDB_NUMFIELD_KEYTRACK_ROOT 176
#define IDB_MSEG_LOOP_MODE 305
#define IDB_LFO_MSEG_EDIT 177
#define IDB_LFO_PRESET_MENU 178
#define IDB_MSEG_SNAPVALUE_NUMFIELD 306
#define IDB_MODSOURCE_SHOW_LFO 179
#define IDB_MSEG_EDIT_MODE 307
#define IDB_ABOUT_LOGOS 180
#define IDB_ABOUT_BG 158
#define IDB_VUMETER_BARS 181
#define IDB_MIDI_LEARN 182
// == /SVG == Do not remove this comment
